baseURL = "/"
languageCode = "en-us"
title = "n3wscott"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 20
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Flipping tables."
  facebook = ""
  twitter = "https://twitter.com/n3wscott"
  instagram = ""
  youtube = ""
  github = "https://github.com/n3wscott"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = "@n3wscott"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/hero.jpg"
  recent_posts_number = 5